# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca28df49de8e40f9a016fa730c74356cc7c40d4316e26975481060ef4613c49e68d0665390a243d9bcea55eb0b663dcdda70f847b414fdfea117516bf21efdf7

test:
  secret_key_base: 9b4a4e0f1e4603e1c201a3bd887d05f62d99052cb076b9ae04b13ff73c5a4f4f52970a50c3956ae1e44f2a4a51e5082e49161147df650551ce453f0956c6dd3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
